// <auto-generated />
namespace mtsToolsWebAPI.EFCore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class menuinfonotnull : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(menuinfonotnull));
        
        string IMigrationMetadata.Id
        {
            get { return "202007230801465_menuinfonotnull"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
